### PR TITLE
Is escapechar broken?

### PR DESCRIPTION
**Pull request by gustafsson**
The documentation states:

```
    •    quotechar::Union{Char,UInt8}: the character that indicates a quoted field that may contain the delim or newlines; default '"'
      
    •    escapechar::Union{Char,UInt8}: the character that escapes a quotechar in a quoted field; default '\'
```

I interpret this as the following csv file
```
x
"a\"b"
```
should be parsed as `DataFrame(x="a\"b")`. But this isn't the case. Am I missing something or is something broken?

Similarly the test of #86 didn't test that `escapechar='"'` transformed `""` to `"`. The test looks broken to me.

### CODE REVIEW

**Comment by nalimilan** [comment]
See also https://github.com/JuliaData/CSV.jl/issues/166.

**Comment by gustafsson** [comment]
Isn't #166 a discussion about what the default should be?

My apologies for being so blunt, but this PR is more about that I wasn't able to find at least one example file where at least one `escapechar` works (including the default).

---

Let's take another example from: https://discourse.julialang.org/t/problem-related-to-csv-read-and-strings/9595/8

```
julia> open("/tmp/tst.csv", "w") do f write(f, IOBuffer("a,b,c\r\n104652,\"Thanks  \\\",a\r\n")) end

shell> cat /tmp/tst.csv
a,b,c
104652,"Thanks  \",a

julia> CSV.read("/tmp/tst.csv", quotechar='"')
0×3 DataFrames.DataFrame
```

This seems to be another issue with empty last lines. But

```
julia> open("/tmp/tst.csv", "w") do f write(f, IOBuffer("a,b,c\r\n104652,\"Thanks  \\\",a")) end

shell> cat /tmp/tst.csv
a,b,c
104652,"Thanks  \",a
julia> CSV.read("/tmp/tst.csv", quotechar='"')
1×3 DataFrames.DataFrame
│ Row │ a      │ b             │ c       │
├─────┼────────┼───────────────┼─────────┤
│ 1   │ 104652 │ Thanks  \\",a │ missing │
```

**Comment by nalimilan** [comment]
> Isn't #166 a discussion about what the default should be?

Yeah, I just mentioned it because we wondered how it should work when that issue was filed. But I have no idea how broken it is.

**Comment by quinnj** [comment]
Alright, I've finally got a handle on this and I'm a bit embarrassed. Unfortunately, I never took the time to fully think through how escape characters work and only ever considered their implications in escaping delimiters/newlines, but not in how they should be removed in the final data. I _should_ have got this because we do this [exact same thing](https://github.com/quinnj/JSON2.jl/blob/0a37062e539b81a28a4e9e0e7661e43315ed424e/src/strings.jl#L124) in JSON2.jl. I just tagged a release of Parsers.jl that ensures we `unescape` strings if escape characters are found while parsing. Sorry for the hassle and confusion everyone.

**Pull request closed without merging**
