### PR TITLE
New CSV.Rows iterator

### PR DESCRIPTION
**Pull request by quinnj**
cc: @GregPlowman

I'm liking the code here more than what's in #444; it's less code duplication, simpler overall, and provides a very memory efficient way to loop thru an entire file.

I'd appreciate if people could play around with this and let me know what they think and any issues they have/see.

Note that there's a `CSV.Rows` specific keyword argument `reusebuffer::Bool=false` which controls whether iterating over rows will use a single value buffer or allocate a fresh buffer for each iteration (the default). That means if you do `rows = collect(CSV.Rows(file))`, by default you'll have a collection of "rows" that will work just fine. But if you're doing
```julia
for row in CSV.Rows(file; reusebuffer=true)
    # do stuff w/ row
end
```
You can avoid that little extra allocation on each iteration by just re-using a single buffer.

### CODE REVIEW

**Comment by quinnj** [comment]
Alright, I've added docs, tests, and done some performance checking and I think this is ready to go.

**Comment by GregPlowman** [comment]
I'm just starting to try this out.

Here's a couple of preliminary benchmarks (hopefully I'm using the API correctly).
So far, looks good. Later, I'll try out with larger files and compare memory usage.
Next week I'll have a real-world case to try out.

Method | Parse time | Iterate time
--- | --- | ---
CSV.File | 41.5s | 41.6s
CSV.Rows | 2.8s | 45.7s
CSV.Rows, reusebuffer=true | 2.6s | 35.7s

A couple of incidental points:
As an aside, why can't we use a positional integer to index into `CSV.row` (from iterating `CSV.File`)?
I also learned the `Parsers.parse` is faster than `Base.parse`. Thanks!

Here's the code. 
```
using CSV, Parsers, DataFrames

filename = "test.csv"
rows = 10^8
df = DataFrame(A = rand('A':'Z', rows), B = rand(1:1000, rows), C = rand(Float64, rows));
CSV.write(filename, df)

function f1(csvfile::CSV.File)
    s = 0.0
    for row in csvfile
        a = row.A
        b = row.B
        c = row.C
        if "A" <= a <= "E"
            x = b * c
        else
            x = b + c
        end
        s += x
    end
    return s
end

function f2(csvrows::CSV.Rows, coltypes)
    s = 0.0
    for row in csvrows
        a = row[1]
        b = Parsers.parse(Int, #=coltypes[2],=# row[2])
        c = Parsers.parse(Float64, #=coltypes[3],=# row[3])
        if "A" <= a <= "E"
            x = b * c
        else
            x = b + c
        end
        s += x
    end
    return s
end

using BenchmarkTools
coltypes = eltypes(df)
@time csvfile = CSV.File(filename)
@time csvrows1 = CSV.Rows(filename)
@time csvrows2 = CSV.Rows(filename; reusebuffer=true)
@btime f1($csvfile)
@btime f2($csvrows1, $coltypes)
@btime f2($csvrows2, $coltypes)
```

**Comment by quinnj** [comment]
Thanks @GregPlowman for trying this out! The initial results look encouraging. Yeah, we can add `getindex` for `CSV.Row`.

**Comment by GregPlowman** [comment]
Here's some further results with very large files (10^8, 10^9 , 10^10 rows). 
(Julia v1.1.1, Windows 10, 128 GB memory)

There is definitely some memory savings with `CSV.Row`, but huge 10^10 row file can only be read by basic `readline, split, parse` method (which effectively streams from input file).

I still think something weird in going on with Windows `mmap`.

Code and results below.
Might be interesting to see results for non-Windows systems.

| 10^8 rows | Initial load time | Iterate time
| --------- | ------------------| ------------
CSV.File |	46s	| 33s
CSV.Rows | 18s | 53s
CSV.Rows, reusebuffer=true	| 4s | 52s
readline, split, parse | N/A | 92s 

| 10^9 rows | Initial load time | Iterate time
| --------- | ------------------| ------------
CSV.File |	446s	| 330s
CSV.Rows | 175s | 533s
CSV.Rows, reusebuffer=true	| 32s | 512s
readline, split, parse | N/A | 894s

| 10^10 rows | Initial load time | Iterate time
| --------- | ------------------| ------------
CSV.File |	ERROR*	| N/A
CSV.Rows | ERROR* | N/A
CSV.Rows, reusebuffer=true	| ERROR* | N/A
readline, split, parse | N/A |  9004s

\* ERROR: could not create file mapping: The operation completed successfully.

```
CSV.File

Memory: 128 GB, 124 GB free
Processing test_100000000.csv, nrows = 10^8
 46.901018 seconds (77.45 M allocations: 629.118 MiB, 0.48% gc time)
 33.067428 seconds (548.94 M allocations: 8.181 GiB, 1.25% gc time)
Memory: 128 GB, 117 GB free

Memory: 128 GB, 117 GB free
Processing test_1000000000.csv, nrows = 10^9
446.612631 seconds (695.61 M allocations: 2.592 GiB, 0.03% gc time)
330.971941 seconds (5.49 G allocations: 81.793 GiB, 1.10% gc time)
Memory: 128 GB, 56 GB free

Memory: 128 GB, 56 GB free
Processing test_10000000000.csv, nrows = 10^10
ERROR: could not create file mapping: The operation completed successfully.
```

```
CSV.Rows

Memory: 128 GB, 124 GB free
Processing test_100000000.csv, nrows = 10^8
 18.037532 seconds (956.79 k allocations: 49.120 MiB, 0.06% gc time)
 53.868630 seconds (970.68 M allocations: 31.668 GiB, 4.55% gc time)
Memory: 128 GB, 122 GB free

Memory: 128 GB, 122 GB free
Processing test_1000000000.csv, nrows = 10^9
175.612800 seconds (79 allocations: 6.328 KiB)
533.730188 seconds (9.67 G allocations: 315.178 GiB, 4.17% gc time)
Memory: 128 GB, 101 GB free

Memory: 128 GB, 101 GB free
Processing test_10000000000.csv, nrows = 10^10
ERROR: could not create file mapping: The operation completed successfully.
```

```
CSV.Rows, reusebuffer=true

Memory: 128 GB, 124 GB free
Processing test_100000000.csv, nrows = 10^8
  3.953053 seconds (956.79 k allocations: 49.120 MiB, 0.25% gc time)
 52.114704 seconds (870.68 M allocations: 21.237 GiB, 3.25% gc time)
Memory: 128 GB, 122 GB free

Memory: 128 GB, 122 GB free
Processing test_1000000000.csv, nrows = 10^9
 32.135494 seconds (79 allocations: 6.328 KiB)
512.313155 seconds (8.67 G allocations: 210.869 GiB, 2.91% gc time)
Memory: 128 GB, 101 GB free

Memory: 128 GB, 101 GB free
Processing test_10000000000.csv, nrows = 10^10
ERROR: could not create file mapping: The operation completed successfully.
```

```
readline, split, parse

Memory: 128 GB, 124 GB free
Processing test_100000000.csv, nrows = 10^8
 92.844546 seconds (2.07 G allocations: 70.414 GiB, 5.96% gc time)
Memory: 128 GB, 124 GB free

Memory: 128 GB, 124 GB free
Processing test_1000000000.csv, nrows = 10^9
894.768406 seconds (20.67 G allocations: 702.649 GiB, 4.50% gc time)
Memory: 128 GB, 124 GB free

Memory: 128 GB, 124 GB free
Processing test_10000000000.csv, nrows = 10^10
9004.233298 seconds (206.74 G allocations: 6.862 TiB, 4.60% gc time)
Memory: 128 GB, 124 GB free
```

Here's the code:
```
using CSV, Parsers, DataFrames

function CreateFile(filename, n)
    open(filename, "w") do io
        println(io, "A,B,C")    # header
        for i = 1:n
            println(io, rand('A':'Z'), ",", rand(1:1000), ",", rand())
        end
    end
end

function foo(a::AbstractString, b::Int, c::Float64)
    if "A" <= a <= "E"
        x = b * c
    else
        x = b + c
    end
    return x
end

function test(csvfile::CSV.File)
    s = 0.0
    for row in csvfile
        a = row.A
        b = row.B
        c = row.C
        s += foo(a, b, c)
    end
    return s
end

function test(rows::CSV.Rows, coltypes)
    s = 0.0
    for row in rows
        a = row[1]
        b = Parsers.parse(coltypes[2], row[2])
        c = Parsers.parse(coltypes[3], row[3])
        s += foo(a, b, c)
    end
    return s
end

function test(filename::AbstractString, coltypes)
    s = 0.0
    #for line in eachline(filename)
    open(filename, "r") do io
        readline(io)    # skip header
        while !eof(io)
            line = readline(io)
            row = split(line, ",")
            a = row[1]
            b = Parsers.parse(coltypes[2], row[2])
            c = Parsers.parse(coltypes[3], row[3])
            s += foo(a, b, c)
        end
    end
    return s
end


function PrintMemory()
    println("Memory: ", round(Int, Sys.total_memory()/2^30), " GB, ", round(Int, Sys.free_memory()/2^30), " GB free")
end


const coltypes = (String, Int, Float64)
cd(raw"D:\Temp")

for n in (10,) #(8, 9, 10)
    GC.gc()
    println()
    PrintMemory()

    nrows = 10^n
    filename = string("test_", nrows, ".csv")
    println("Processing ", filename, ", nrows = 10^", n)
    isfile(filename) || CreateFile(filename, nrows)

    @time csvfile = CSV.File(filename)
    @time test(csvfile)

    #@time csvrows1 = CSV.Rows(filename)
    #@time test(csvrows1, coltypes)

    #@time csvrows2 = CSV.Rows(filename, reusebuffer=true)
    #@time test(csvrows2, coltypes)

    #@time test(filename, coltypes)

    PrintMemory()
    println()
    GC.gc()
end
```

**Pull request merged**
