### PR TITLE
Fix a few issues for (USER | MISSING) column types

### LINKED ISSUE #592: Bug with CSV.File(, select =...)
```
using HTTP, CSV
response = HTTP.request("GET", "https://covidtracking.com/api/states/daily.csv")
@assert response.status == 200
# This doesn't work
data = File(response.body,
            select = [:state, :dateChecked, :positive, :negative, :pending, :hospitalized, :death]) |>
    DataFrame
thread = 1 warning: only found 16 / 17 columns on data row: 1485. Filling remaining columns with `missing`
ERROR: BoundsError: attempt to access 0-element Array{UInt64,1} at index [1485]
Stacktrace:
 [1] setindex! at ./array.jl:825 [inlined]
 [2] parsetape(::Val{false}, ::Bool, ::Int64, ::Dict{Int8,Int8}, ::Array{Array{UInt64,1},1}, ::Array{Array{UInt64,1},1}, ::Array{UInt8,1}, ::Int64, ::Int64, ::Int64, ::Nothing, ::Array{Int64,1}, ::Float64, ::Array{Dict{String,UInt64},1}, ::Array{UInt64,1}, ::Int64, ::Array{Int8,1}, ::Array{Int64,1}, ::Bool, ::Parsers.Options{false,false,true,false,Missing,UInt8,Nothing}, ::Bool) at /Users/jbsc/.julia/packages/CSV/7Dav7/src/CSV.jl:766
 [3] file(::Array{UInt8,1}, ::Int64, ::Bool, ::Int64, ::Nothing, ::Int64, ::Int64, ::Bool, ::Nothing, ::Bool, ::Bool, ::Nothing, ::Array{Symbol,1}, ::Nothing, ::Array{String,1}, ::String, ::Nothing, ::Bool, ::Char, ::Nothing, ::Nothing, ::Char, ::Nothing, ::UInt8, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Dict{Int8,Int8}, ::Bool, ::Float64, ::Bool, ::Bool, ::Bool, ::Bool, ::Nothing) at /Users/jbsc/.julia/packages/CSV/7Dav7/src/CSV.jl:520
 [4] #File#15 at /Users/jbsc/.julia/packages/CSV/7Dav7/src/CSV.jl:262 [inlined]
 [5] top-level scope at REPL[116]:1
# This works
data = File(response.body) |>
        DataFrame
```
Version Info
```
julia> versioninfo(verbose = true)
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  uname: Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64 i386
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz: 
              speed         user         nice          sys         idle          irq
       #1  2500 MHz     540434 s          0 s     489413 s    2853137 s          0 s
       #2  2500 MHz      62616 s          0 s      83057 s    3736642 s          0 s
       #3  2500 MHz     500394 s          0 s     392598 s    2989364 s          0 s
       #4  2500 MHz      61659 s          0 s      65015 s    3755634 s          0 s
       #5  2500 MHz     438023 s          0 s     324294 s    3120021 s          0 s
       #6  2500 MHz      61116 s          0 s      55396 s    3765789 s          0 s
       #7  2500 MHz     391988 s          0 s     278578 s    3211757 s          0 s
       #8  2500 MHz      60848 s          0 s      48892 s    3772554 s          0 s
       
  Memory: 16.0 GB (296.625 MB free)
  Uptime: 576360.0 sec
  Load Avg:  2.23681640625  2.38134765625  2.416015625
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
  JULIA_NUM_THREADS = 1
  PATH = /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
  HOME = /Users/jbsc
  XPC_FLAGS = 0x0
  TERM = xterm-256color
```

### PR DESCRIPTION
**Pull request by quinnj**
Fixes #592. With the new `select`/`drop` keyword arguments, we'll now be
seeing many more column types w/ typecodes like `(USER | MISSING)`.
Which are handled specially when parsing. In particular, the parsing
tape is allocated with length 0. For parsing a column of this type, we
just consume the cell in the file without storing anything. The problem
in the original issue was in the tape re-allocation code, we assumed
every tape had length to copy from old tape to new tape. There was
another issue in the invalid row checking code where if a row didn't
have enough columns, we usually set the value of each unparsed column in
the row to `missing`, but that doesn't matter or is needed for `(USER |
MISSING)` columns.

### CODE REVIEW

**Comment by Nosferican** [comment]
Thanks! Could we get a patch tag with this fix?

**Comment by Nosferican** [comment]
I could make the PR with the Project.toml patch bump if that helps.

**Comment by quinnj** [comment]
Ok, just submitted a patch release; I had already started a refactor that I was a little uncomfortable w/ tagging, so I just cherry-picked it into a 0.6 branch.

**Comment by Nosferican** [comment]
Thanks!

**Pull request merged**
