### PR TITLE
add CategoricalArrays.jl version 0.7 support

### LINKED ISSUE #502: Update compatibility with CategoricalArrays.jl
CSV.jl requires CategoricalArrays.jl to be 0.5 or 0.6 only.

@nalimilan - given the new release when this should be synced? Now?

### PR DESCRIPTION
**Pull request by bkamins**
Fixes #502

### CODE REVIEW

**Comment by bkamins** [comment]
@quinnj can you please have a look at this (I expect that some packages in ML ecosystem will depend on CategoricalArrays.jl 0.7 soon and then we will start getting allowed version conflicts). Thank you!

**Comment by bkamins** [comment]
Thank you! @quinnj Are you planning to add something else to CSV.jl before tagging the release?

**Comment by quinnj** [comment]
I've been working on a refactoring of the internals for #432, but if you want to do a quick patch release for this change, feel free.

**Comment by bkamins** [comment]
Thank you for looking into #432!

I would do a patch release (as now we have a conflict with released CategoricalArrays.jl 0.7, and it introduces a breaking functionality).

Just, for safety, please confirm that #497 can be safely included in this patch release (I have looked through it and I think it can, but maybe there is something breaking I did not spot).

**Comment by quinnj** [comment]
Yes, that's fine.

**Pull request merged**
