### PR TITLE
Port to CategoricalArrays 0.8

### PR DESCRIPTION
**Pull request by nalimilan**
The change to `levels!` implies that all reference codes will be updated at the end to match the new order of levels (unless they were already sorted).

Requires the yet-to-be released CategoricalArrays 0.8.

### CODE REVIEW

**Comment by bkamins** [comment]
Can it be merged then?

**Comment by nalimilan** [comment]
It needs DataFrames 0.21 to pass CI.

**Comment by bkamins** [comment]
So this means that we have to coordinate releasing DataFrames.jl and CSV.jl? In this case maybe in this PR you can bump DataFrames.jl version and CSV.jl version in Project.toml?

**Comment by nalimilan** [comment]
Well we have to release DataFrames first, and then ideally CSV.jl soon after that. If we don't do it, people who have CSV installed will stay at DataFrames 0.20, which isn't the end of the world but is... annoying. :-) But we also have to port many other packages, like RCall.

**Comment by quinnj** [comment]
I could do the next CSV release at any point now. I'm tracking down loose ends and kicking the tires on more speculative features; and I'm going to try to do another thorough review of performance/memory. But nothing release blocking. So I'll let @nalimilan drive a coordinated release for CategoricalArrays/DataFrames and CSV can tag along.

**Comment by quinnj** [comment]
@nalimilan, should we merge here and do a new release?

**Comment by bkamins** [comment]
We need to sync this with DataFrames.jl release.

**Comment by quinnj** [comment]
Ah right; I think in my mind, I was worried we were holding the DataFrames release because of this, but I suspect @nalimilan will known when to merge and then we can tag.

**Comment by bkamins** [comment]
The releases must be synced. We need to finish https://github.com/JuliaData/DataFrames.jl/pull/2214 (complex) and https://github.com/JuliaData/DataFrames.jl/pull/2196 (easy) and then we can make a release of DataFrames.jl.

**Comment by bkamins** [comment]
Version of CSV.jl in Project.toml needs to be changed also (unless you want to do it in a separate PR)

**Comment by bkamins** [comment]
CI looks good now - thank you!

**Comment by nalimilan** [comment]
https://github.com/JuliaRegistries/General/pull/14243

**Pull request merged**
