### PR TITLE
improve time to first csv load

### PR DESCRIPTION
**Pull request by rafaqz**
This PR aims to at least partially solve #974

This first commit demonstrates that simply breaking up large unstable functions can greatly improve compilation time. Splitting `File` here into threaded and single threaded contexts means only the one we are using gets compiled. For me this shaves the time from #974 from 16seconds to 12 seconds. Without changing anything else.

There are probably a lot more potential for this. The functions in file.jl all seem to be too long.

### CODE REVIEW

**Comment by bkamins** [comment]
bravo!

**Comment by rafaqz** [comment]
Fixing type stability and adding precompilination runs brings the total load time down to 7 seconds, and `using CSV` is 1 second.

There is another second available by removing the `@refargs` macro so `Context` precompiles, but I'm not sure what the purpose of this macro is?

**Comment by quinnj** [comment]
Sorry for not being able to review earlier; I think this is exciting stuff! One comment I'll make is that a lot of the current code organization was done in an effort to avoid _recompilation_ costs as much as possible. It's become clear to me now that doing that has brought on a pretty severe cost for TTFR, but I'd also like to keep that in mind as we make efforts to reduce TTFR. I.e. some of the changes here mean that if you slightly change a keyword argument, we have to pay significant compilation costs again, which hopefully we can avoid. In CSV.jl early days, we were at the opposite end of the spectrum where every single call to `CSV.File` almost guaranteed recompiling everything; but I think I agree that we've probably swung back too far the other way by compiling _too_ much when you initially call `CSV.File` and we can allow more incremental compilation as various features are actually used/needed while parsing.

As a reviewer comment, it would be nice to probably split this up into separate PRs? As-is, it's very hard to review since there's so much moving/changing around.

**Comment by rafaqz** [comment]
I figured something like that might have been the case. If we can get precompilation working nearly everywhere and functions are broken up enough that they are decoupled, we should hopefully only see minor recompilation for small changes. Its really the file.jl internals that take a long time and they are precompiling for all common types now it seems. `Context` takes under a second the first time, so subsequent changes shouldn't be too bad either. 

I know this PR is currently pretty messy and buggy... its pretty much a blind search for type stability with Cthulhu.jl. 

Unfortunately its hard to split up the PR while working on it because precompilation only works past some certain threshold of stability and function size (that I don't totally understand to be honest), and before that most things have no noticeable effect. Once I can lock down everything required to make this work I can go back and split it all up into separate changes.

**Comment by rafaqz** [comment]
Precompile in Parsers.jl helps a lot here: https://github.com/JuliaData/Parsers.jl/pull/108

TTFX with both of these changes is now about 4 seconds.

**Comment by rafaqz** [comment]
There another 30-40% TTFX improvement in some of this code, but some changes are unnecessary now - this branch had larger gains without the Paraers.jl fix.

The changes here that still make sense will be more controversial for more modest improvements, so won't be high priority for me.

**Comment by rafaqz** [comment]
Probably restructuring Context and the preloaded of that would be the most obvious next step.

**Comment by ViralBShah** [comment]
I suppose this is outdated and can be closed.

**Comment by rafaqz** [comment]
I didnt mention here but after the later fix to Parsers.jl (removing just 4 `@inline`s 😂) this PR stopped doing much:

https://github.com/JuliaData/Parsers.jl/pull/1140

All the `@noinlines` and function barriers were effective because of the constants that Parsers.jl inlined. There are probably a few type stability things here worth keeping, but may starting a new PR and benchmarking without the Parsers.jl problems would make more sense.

**Pull request closed without merging**
