### PR TITLE
Fix the problem in Example page since v0.10

### PR DESCRIPTION
**Pull request by hungpham3112**
Not check yet, I'm not familiar with `Documenter.jl` and I can't run make.jl in my local machine so need to check before merge. Thanks.

v0.10.11:
image

### CODE REVIEW

**Review by quinnj — APPROVED** [review]
Thanks @hungpham3112!

**Comment by hungpham3112** [comment]
Hi, I checked the document but still see the error. The document haven't update yet?

image

**Comment by giordano** [comment]
@hungpham3112 there haven't been stable releases of CSV.jl after your PR, yet, but the fix is visible in the dev docs: https://csv.juliadata.org/dev/examples.html

**Comment by quinnj** [comment]
I just kicked off a new patch release

**Pull request merged**
