### PR TITLE
Add a CSV.View type that ignores any type information while parsing a…

### PR DESCRIPTION
**Pull request by quinnj**
…nd provides the same interface as CSV.File

cc: @GregPlowman

### CODE REVIEW

**Comment by nalimilan** [comment]
Can you explain what's the advantage of this?

**Comment by quinnj** [comment]
Parsing an entire file via `CSV.View` is about 10-20% faster, while using about half the memory footprint. So it should alleviate problems that users sometimes run into on windows like #443. What they get back is essentially an object w/ the same interface as `CSV.File`, but each column is assumed to be String type.

Given how easy it was to implement this, and for the amount of code duplication, I'm leaning towards not merging this due to the relatively meager performance gain. I'm also working on the idea of a `CSV.Rows` type to iterate rows w/ a minimal memory footprint, also assuming `String` type for each column that I think provides a similar benefit with essentially no memory footprint.

**Comment by GregPlowman** [comment]
Thanks for looking at this.

> Parsing an entire file via CSV.View is about 10-20% faster, while using about half the memory footprint. So it should alleviate problems that users sometimes run into on windows like #443. What they get back is essentially an object w/ the same interface as CSV.File, but each column is assumed to be String type.
> 
> Given how easy it was to implement this, and for the amount of code duplication, I'm leaning towards not merging this due to the relatively meager performance gain. I'm also working on the idea of a CSV.Rows type to iterate rows w/ a minimal memory footprint, also assuming String type for each column that I think provides a similar benefit with essentially no memory footprint.

Well for me it's not necessarily the "performance gain" that is most important (but faster is better), but whether arbitrarily large files can be processed or not. Halving the memory footprint is significant, but there will always be a file twice as large that will have the same issue of running out of memory.

An approach that scales indefinitely with file size would seem useful. Files could be processed row-by-row, with fixed memory requirements. Of course there could be optimizations such as buffering in chunks etc.

**Comment by nalimilan** [comment]
OK, thanks. I agree duplicating all of that code isn't necessarily worth it: as @GregPlowman says, what would be very useful is a way to avoid allocating a copy at all (which the old implementation did, but with issues regarding type detection).

**Comment by quinnj** [comment]
> An approach that scales indefinitely with file size would seem useful. Files could be processed row-by-row, with fixed memory requirements. Of course there could be optimizations such as buffering in chunks etc.

Yeah, that's why I'm favoring #445 over this PR, because it can handle arbitrarily large files w/ a fixed-size buffer. There are still ways we can optimize the memory use of CSV.File, even incorporating some of the ideas here, so I think I'll close this PR for now.

**Pull request closed without merging**
