### PR TITLE
fixed 0.7 deprecation warning

### PR DESCRIPTION
**Pull request by MLackner**
specifically the `replace` function

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks. Could you revert the addition of Manifest.toml (which shouldn't generally be committed)?

**Comment by MLackner** [comment]
Okay... Removed it :)

**Comment by nalimilan** [comment]
Thanks. Though I guess we should remove REQUIRE if we add Project.toml?

**Comment by MLackner** [comment]
Frankly, I have no idea at which point the REQUIRE file should be replaced by the Project.toml file. I just put the Project.toml file with a genereic uuid in there because my tests were complaining about missing dependencies in CSV.jl. So this was just to get my code working again with 0.7.

**Comment by quinnj** [comment]
Sorry, I pushed a fix separate from this. Thanks for the contribution though!

**Comment by quinnj** [comment]
Also, just as FYI: packages still require REQUIRE files until METADATA.jl has been fully transitioned to expect Project.toml files. It's also not discouraged to commit Manifest.toml files, but package maintainers need to be careful when committing to ensure the Manifest represents a valid environment for any user/maintainer (i.e. no local dev paths, etc.).

**Pull request closed without merging**
