### PR TITLE
Improve handling of missing values

### LINKED ISSUE #153: Assume columns can have missing values by default
The current behavior of _CSV.jl_ is to scan columns until ```row_for_type_detect``` iterations have passed and infer their type.

However, for large files with few null cells, this force to set ```row_for_type_detect``` to the maximum number of rows, as the heuristic cannot detect if the last row of the file might contain null cells for instance.

--------

### Solution

One workaround would be to assume that rows can contain null cells by default, except if the user disable it. This was the behavior in ```DataFrames.readtable``` for instance.

Another would be to have a manual flag in ```CSV.Options``` to assume that all rows can contain null values.

### PR DESCRIPTION
**Pull request by nalimilan**
Replace the `nullable::Union{Bool,Missing}` argument with `allowmissing::Symbol`, with possible choices `:all`, `:auto` and `:none`, and make `:all` the default to avoid errors when the first missing value appears beyond rows used for type detection. Also avoid overriding types specified explicitly via the types argument,
which allows for more flexibility.

While deprecating `nullable`, also deprecate `null` in favor of `missingstring` for consistency with `truestring` and `falsestring`.

Fixes #153, https://github.com/JuliaData/CSV.jl/issues/159.

### CODE REVIEW

**Comment by quinnj** [comment]
I went ahead and resolved the conflicts here; I'm seeing some weird failures on 0.7 where the `missingstring` sometimes disappears (i.e. when we try to access it during reading, it's empty even though we set it upon construction). Still need to do some more debugging, but the rest looks good.

**Comment by nalimilan** [comment]
I've added a commit to get tests to pass on 0.6. They also pass locally on 0.7 with DataStreams master. I haven't seen the bug you mention, though. Good to merge?

**Comment by nalimilan** [comment]
Bump! OK to merge?

**Comment by andreasnoack** [comment]
See https://github.com/JuliaIO/JSON.jl/commit/f05dd3d26976ae8310cfb512cf0106505e95b51b#commitcomment-28964065. It also applies here.

**Pull request merged**
